from pathlib import Path
import subprocess,os,json,re,hashlib
b=Path('/home/nate/Oxy/.agent-evidence');e=b/'i04-final-registry-native-types-20261004';m=json.loads(Path('/home/nate/Oxy/oxy/.worktrees/1519-real-oauth-browser-20261003/.integration-evidence/oauth1519-1n8d1xvu/manifest.json').read_text());signRoot=Path('/home/nate/Oxy/oxy/.worktrees/1519-native-provider-instrumentation-20261003/scripts/rehearsal/android-device-session');config=(signRoot/'host/build.gradle.kts').read_text();store=re.search(r'storePassword\s*=\s*"([^"]+)"',config).group(1);key=re.search(r'keyPassword\s*=\s*"([^"]+)"',config).group(1);alias=re.search(r'keyAlias\s*=\s*"([^"]+)"',config).group(1);receipts=[]
for lane,client in [('mention','nativeFirst'),('allo','nativeSecond')]:
 fixture=b/'i04-final-registry-fixtures'/lane;env={k:v for k,v in os.environ.items()if k in ['PATH','HOME','LANG','LC_ALL','TMPDIR']};env.update(ANDROID_HOME='/home/nate/Android/Sdk',JAVA_HOME='/usr/lib/jvm/java-21-openjdk-amd64',CI='1',EXPO_NO_DOTENV='1',EXPO_PUBLIC_OXY_NATIVE_ACCEPTANCE='1',EXPO_PUBLIC_OXY_NATIVE_SIBLING=lane,EXPO_PUBLIC_OXY_CLIENT_ID=m['clients'][client]['clientId']);args=['./gradlew',':app:assembleDebug','--no-daemon','--max-workers=2','-Dorg.gradle.jvmargs=-Xmx3g','-PreactNativeArchitectures=x86_64']
 with(e/f'{lane}-gradle.log').open('x')as f:r=subprocess.run(args,cwd=fixture/'android',env=env,stdout=f,stderr=subprocess.STDOUT,timeout=1800)
 assert r.returncode==0,lane
 apk=fixture/'android/app/build/outputs/apk/debug/app-debug.apk';signed=e/(lane+'-registry-signed.apk');assert not signed.exists();env.update(OXY1519_SIGN_STORE=store,OXY1519_SIGN_KEY=key);signer='/home/nate/Android/Sdk/build-tools/36.0.0/apksigner'
 with(e/f'{lane}-sign.log').open('x')as f:subprocess.run([signer,'sign','--ks',str(signRoot/'.signing/allowed.jks'),'--ks-key-alias',alias,'--ks-pass','env:OXY1519_SIGN_STORE','--key-pass','env:OXY1519_SIGN_KEY','--out',str(signed),str(apk)],env=env,stdout=f,stderr=subprocess.STDOUT,check=True)
 result=subprocess.check_output([signer,'verify','--print-certs',str(signed)],env=env,text=True);(e/f'{lane}-certificate.txt').write_text(result);receipts.append({'lane':lane,'apk':str(signed),'sha256':hashlib.sha256(signed.read_bytes()).hexdigest(),'bytes':signed.stat().st_size,'command':args,'installed':False});(e/'apk-builds.json').write_text(json.dumps(receipts,indent=2)+'\n')
print('Two signed fixture APKs built; no ADB')
