/**
 * Oxy Updates code-signing tests. Uses a REAL keypair + certificate generated by
 * `@expo/code-signing-certificates` (the exact machinery the expo-updates client
 * verifies against), so the signature assertions are genuine: we sign with the
 * service and verify with node:crypto against the certificate's public key.
 */

import crypto from 'crypto';
import {
  generateKeyPair,
  generateSelfSignedCodeSigningCertificate,
  convertCertificateToCertificatePEM,
  convertKeyPairToPEM,
} from '@expo/code-signing-certificates';
import {
  signPartBytes,
  isCodeSigningConfigured,
  resetSigningKeyCache,
  CodeSigningNotConfiguredError,
  CODE_SIGNING_KEY_ID,
} from '../signing.service';

const keyPair = generateKeyPair();
const validityNotBefore = new Date();
const validityNotAfter = new Date();
validityNotAfter.setFullYear(validityNotAfter.getFullYear() + 1);
const certificate = generateSelfSignedCodeSigningCertificate({
  keyPair,
  validityNotBefore,
  validityNotAfter,
  commonName: 'Oxy Updates Test',
});
const { privateKeyPEM } = convertKeyPairToPEM(keyPair);
const certificatePEM = convertCertificateToCertificatePEM(certificate);
const publicKey = new crypto.X509Certificate(certificatePEM).publicKey;

const originalEnv = process.env.UPDATES_CODE_SIGNING_PRIVATE_KEY;

function verify(bytes: Buffer, signatureBase64: string): boolean {
  return crypto
    .createVerify('RSA-SHA256')
    .update(bytes)
    .verify(publicKey, Buffer.from(signatureBase64, 'base64'));
}

function parseSignatureHeader(header: string): { sig: string; keyid: string } {
  const match = header.match(/^sig="([^"]+)", keyid="([^"]+)"$/);
  if (!match) {
    throw new Error(`Unexpected signature header shape: ${header}`);
  }
  return { sig: match[1], keyid: match[2] };
}

describe('updates signing.service', () => {
  afterEach(() => {
    if (originalEnv === undefined) {
      delete process.env.UPDATES_CODE_SIGNING_PRIVATE_KEY;
    } else {
      process.env.UPDATES_CODE_SIGNING_PRIVATE_KEY = originalEnv;
    }
    resetSigningKeyCache();
  });

  test('reports not configured and throws when no key is set', () => {
    delete process.env.UPDATES_CODE_SIGNING_PRIVATE_KEY;
    resetSigningKeyCache();
    expect(isCodeSigningConfigured()).toBe(false);
    expect(() => signPartBytes(Buffer.from('anything'))).toThrow(CodeSigningNotConfiguredError);
  });

  test('signs bytes (base64 PEM env) and the signature verifies against the certificate', () => {
    process.env.UPDATES_CODE_SIGNING_PRIVATE_KEY = Buffer.from(privateKeyPEM, 'utf8').toString(
      'base64',
    );
    resetSigningKeyCache();

    expect(isCodeSigningConfigured()).toBe(true);

    const body = Buffer.from(
      JSON.stringify({ id: 'abc', createdAt: '2026-01-01T00:00:00.000Z' }),
      'utf8',
    );
    const header = signPartBytes(body);
    const { sig, keyid } = parseSignatureHeader(header);

    expect(keyid).toBe(CODE_SIGNING_KEY_ID);
    expect(keyid).toBe('main');
    expect(verify(body, sig)).toBe(true);
    // A different byte string must NOT verify against the same signature.
    expect(verify(Buffer.from('tampered'), sig)).toBe(false);
  });

  test('accepts a raw (already-decoded) PEM in the env var too', () => {
    process.env.UPDATES_CODE_SIGNING_PRIVATE_KEY = privateKeyPEM;
    resetSigningKeyCache();

    expect(isCodeSigningConfigured()).toBe(true);
    const header = signPartBytes(Buffer.from('bytes'));
    expect(header).toContain('keyid="main"');
  });

  test('a non-PEM env value disables signing rather than crashing', () => {
    process.env.UPDATES_CODE_SIGNING_PRIVATE_KEY = 'not-a-key';
    resetSigningKeyCache();
    expect(isCodeSigningConfigured()).toBe(false);
    expect(() => signPartBytes(Buffer.from('x'))).toThrow(CodeSigningNotConfiguredError);
  });
});
