module.exports = {
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  testEnvironment: 'jsdom',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  transform: {
    '^.+\\.(ts|tsx)$': ['ts-jest', {
      diagnostics: false,
      tsconfig: {
        jsx: 'react-jsx',
        module: 'commonjs',
        moduleResolution: 'node',
        esModuleInterop: true,
        allowSyntheticDefaultImports: true,
        strict: true,
        skipLibCheck: true,
        resolveJsonModule: true,
        isolatedModules: true,
        target: 'es2020',
        lib: ['es2020', 'dom'],
      },
    }],
  },
  testMatch: [
    '<rootDir>/__tests__/**/*.(test|spec).(ts|tsx|js)',
    '<rootDir>/src/**/__tests__/**/*.(test|spec).(ts|tsx|js)',
    '<rootDir>/src/**/*.(test|spec).(ts|tsx|js)',
  ],
  coverageDirectory: 'coverage',
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/*.stories.{ts,tsx}',
    '!src/**/*.test.{ts,tsx}',
    '!src/**/__tests__/**',
  ],
  moduleNameMapper: {
    '^@expo/vector-icons/createIconSet$': '<rootDir>/__tests__/__mocks__/expo-create-icon-set.tsx',
    '\\.(ttf)$': '<rootDir>/__tests__/__mocks__/static-asset.ts',
    // Resolve workspace deps from TypeScript SOURCE so services tests do not
    // depend on packages being built first (mirrors packages/node/jest.config.cjs).
    '^@oxyhq/contracts$': '<rootDir>/../contracts/src/index.ts',
    '^@oxyhq/protocol$': '<rootDir>/../protocol/src/index.ts',
    '^@oxyhq/core/server$': '<rootDir>/../core/src/server/index.ts',
    '^@oxyhq/core$': '<rootDir>/../core/src/index.ts',
    '^@/(.*)$': '<rootDir>/src/$1',
    '^react-native$': '<rootDir>/__tests__/__mocks__/react-native.ts',
    '^expo-modules-core$': '<rootDir>/__tests__/__mocks__/expo-modules-core.ts',
    '^react-native-reanimated$': '<rootDir>/__tests__/__mocks__/reanimated.ts',
    '^react-native-svg$': '<rootDir>/__tests__/__mocks__/react-native-svg.ts',
    '^@oxyhq/bloom$': '<rootDir>/__tests__/__mocks__/bloom.ts',
    '^@oxyhq/bloom/(.*)$': '<rootDir>/__tests__/__mocks__/bloom.ts',
    '^@expo/vector-icons(/.*)?$': '<rootDir>/__tests__/__mocks__/expo-vector-icons.tsx',
  },
  testTimeout: 10000,
};
