/**
 * `@oxy.so/core` 2.x → 3.0 method map.
 *
 * The single source of truth for the namespace refactor: the codemod
 * (`./codemod.ts`) rewrites call sites from it, and the CHANGELOG table is
 * generated from it.
 *
 * Value forms:
 * - `'users.get'`        → `oxy.users.get(...)` on `OxyServices`
 * - `'server:x.y'`       → `server.x.y(...)` on `OxyServer` (`@oxy.so/core/server`). `OxyServer`
 *                          extends `OxyServices`; a `server:` target inside a namespace
 *                          (`server:assets.metadataByIds`) is a method its server-side
 *                          subclass of that namespace adds.
 * - `null`               → removed (the route does not exist, or it was superseded)
 *
 * `sig` marks a call whose ARGUMENTS change too; the codemod leaves a
 * `// TODO(core-3)` marker there instead of guessing.
 */
export type Target = string | null;

export interface Entry {
  to: Target;
  sig?: string;
}

const e = (to: Target, sig?: string): Entry => (sig ? { to, sig } : { to });

export const METHOD_MAP: Record<string, Entry> = {
  // ── Root (OxyServices core) ──────────────────────────────────────────────
  makeRequest: e('request'),
  getBaseURL: e('baseURL', 'now a property: oxy.baseURL'),
  getCloudURL: e('cloudURL', 'now a property: oxy.cloudURL'),
  getClient: e('http', 'now a property: oxy.http'),
  httpService: e('http'),
  createLinkedClient: e('createLinkedClient'),
  healthCheck: e('health'),
  handleError: e(null),
  getMetrics: e(null),
  getCacheStats: e('cache.stats'),
  clearCache: e('cache.clear'),
  clearCacheEntry: e('cache.delete'),
  clearCacheByPrefix: e('cache.deletePrefix'),
  withAuthRetry: e(null, 'call the method directly; the HTTP layer already refreshes on 401'),
  __resetTokensForTests: e(null),

  // ── session: this client's auth state and its server session ────────────
  setTokens: e('session.setAccessToken'),
  clearTokens: e('session.clear'),
  onTokensChanged: e('session.onChange'),
  getAccessToken: e('session.accessToken', 'now a getter: oxy.session.accessToken'),
  getAccessTokenExpiry: e('session.accessTokenExpiry', 'now a getter'),
  getCurrentUserId: e('session.userId', 'now a getter: oxy.session.userId'),
  hasValidToken: e('session.isAuthenticated', 'now a getter'),
  waitForAuth: e('session.waitForAuth'),
  validate: e('session.validateToken'),
  validateSession: e('session.validate'),
  setDeviceCredentialProvider: e('session.setDeviceCredentialProvider'),
  readDeviceProof: e('session.readDeviceProof'),
  getSessionsBySessionId: e('session.list'),
  logoutSession: e('session.logout'),
  logoutAllSessions: e('session.logoutAll'),

  // ── auth: signing in and the account's credentials ──────────────────────
  register: e('auth.registerKey'),
  requestChallenge: e('auth.requestChallenge'),
  verifyChallenge: e('auth.verifyChallenge'),
  checkPublicKeyRegistered: e('auth.isKeyRegistered'),
  claimSessionByToken: e('auth.claimSession'),
  signInWithSharedIdentity: e('auth.signInWithSharedIdentity'),
  checkUsernameAvailability: e('auth.checkUsername'),
  startEmailVerification: e('auth.email.startVerification'),
  confirmEmailVerification: e('auth.email.confirmVerification'),
  startEmailSignIn: e('auth.email.start'),
  confirmEmailSignIn: e('auth.email.confirm'),
  collectEmailSignIn: e('auth.email.collect'),
  approveEmailSignInLink: e('auth.email.approveLink'),
  signInWithPassword: e('auth.password.signIn'),
  setPassword: e('auth.password.set'),
  completeSecondFactor: e('auth.completeSecondFactor'),
  signUp: e('auth.signUp'),
  getSignInMethods: e('auth.methods'),
  requestReauthEmailCode: e('auth.requestReauthCode'),
  enrollTotp: e('auth.totp.enroll'),
  confirmTotp: e('auth.totp.confirm'),
  disableTotp: e('auth.totp.disable'),
  regenerateTotpBackupCodes: e('auth.totp.regenerateBackupCodes'),
  webauthnRegisterOptions: e(null, 'passkeys are removed (ADR 0030)'),
  webauthnRegisterVerify: e(null, 'passkeys are removed (ADR 0030)'),
  webauthnLoginOptions: e(null, 'passkeys are removed (ADR 0030)'),
  webauthnLoginVerify: e(null, 'passkeys are removed (ADR 0030)'),
  exchangeOAuthCode: e('auth.oauth.exchangeCode'),
  getOAuthUserInfo: e('auth.oauth.userInfo'),
  startCommonsSignIn: e('auth.commons.start'),
  pollCommonsSignIn: e('auth.commons.poll'),
  deliverCommonsSignIn: e('auth.commons.deliver'),
  markCommonsApprovalOpened: e('auth.commons.markOpened'),
  finalizeCommonsOAuth: e('auth.commons.finalizeOAuth'),
  getCommonsApprovalInfo: e('auth.commons.approvalInfo'),
  approveCommonsSignIn: e('auth.commons.approve'),
  denyCommonsSignIn: e('auth.commons.deny'),
  checkEmailAvailability: e(null),

  // ── users: people and their profiles ────────────────────────────────────
  getUserById: e('users.get'),
  getUsersByIds: e('users.getMany'),
  getCurrentUser: e('users.me'),
  getProfileByUsername: e('users.byUsername'),
  getUserByPublicKey: e('users.byPublicKey'),
  getUserBySession: e('users.bySession'),
  getUsersBySessions: e('users.bySessions'),
  searchProfiles: e('users.search'),
  resolveProfile: e('users.resolveHandle'),
  resolveExternalUser: e('users.resolveExternal'),
  getSimilarProfiles: e('users.similar'),
  getProfileRecommendations: e('users.recommendations'),
  updateProfile: e('users.updateMe'),
  updateNotificationPreferences: e('users.updateMe', '(prefs) → ({ notificationPreferences: prefs })'),
  updateUserPreferences: e('users.updateMe', '(prefs) → ({ preferences: prefs })'),
  updateThemePreference: e('users.updateMe', '(theme) → ({ themePreference: theme })'),
  requestAccountVerification: e('users.requestVerification'),
  deleteAccount: e('users.deleteMe', '(confirmText) → (confirmText, { deviceKey: true })'),
  deleteAccountWithEmailCode: e('users.deleteMe', '(confirmText, reauth) → (confirmText, { reauth })'),
  getAccountDeletionOptions: e(null),
  deleteAccountWithPasskey: e(null),
  downloadAccountData: e('identity.export', 'now the signed export (GET /users/me/export)'),
  lookupUsername: e(null),
  getUserStats: e(null),

  // ── follows: one follow graph (users and every other target kind) ───────
  followUser: e('follows.follow'),
  followUsers: e('follows.followMany'),
  unfollowUser: e('follows.unfollow'),
  unfollowUsers: e('follows.unfollowMany'),
  getFollowStatus: e('follows.status'),
  getFollowStatuses: e('follows.statuses'),
  getUserFollowers: e('follows.followers'),
  getUserFollowing: e('follows.following'),
  getUserMutuals: e('follows.mutuals'),
  getMutualUserIds: e('follows.mutualIds'),
  getFollowsOfFollowsIds: e('follows.followsOfFollowsIds'),
  getViewerGraph: e('follows.viewerGraph'),
  invalidateFollowGraphCaches: e(null),
  followTarget: e('follows.followTarget'),
  unfollowTarget: e('follows.unfollowTarget'),
  getFollowTargetStatus: e('follows.targetStatus'),
  setFollowApplicationMode: e('follows.setApplicationMode'),
  restoreFollowInheritance: e('follows.restoreInheritance'),
  ensureFollowTarget: e('follows.ensureTarget'),
  claimFollowNamespace: e('follows.claimNamespace'),
  releaseFollowNamespace: e('follows.releaseNamespace'),
  registerFollowKind: e('follows.registerKind'),
  listFollows: e('follows.list'),

  // ── privacy ──────────────────────────────────────────────────────────────
  getPrivacySettings: e('privacy.settings'),
  updatePrivacySettings: e('privacy.updateSettings'),
  getBlockedUsers: e('privacy.blocked'),
  blockUser: e('privacy.block'),
  unblockUser: e('privacy.unblock'),
  isUserBlocked: e('privacy.isBlocked'),
  getRestrictedUsers: e('privacy.restricted'),
  restrictUser: e('privacy.restrict'),
  unrestrictUser: e('privacy.unrestrict'),
  isUserRestricted: e('privacy.isRestricted'),
  extractUserId: e(null),
  isUserInList: e(null),

  // ── notifications: the in-app inbox and push tokens ─────────────────────
  getNotifications: e('notifications.list'),
  getUnreadCount: e('notifications.unreadCount'),
  markNotificationAsRead: e('notifications.markRead'),
  markAllNotificationsAsRead: e('notifications.markAllRead'),
  deleteNotification: e('notifications.delete'),
  createNotification: e('server:notifications.create'),
  registerPushToken: e('notifications.registerPushToken'),
  unregisterPushToken: e('notifications.unregisterPushToken'),

  // ── assets ───────────────────────────────────────────────────────────────
  assetUpload: e('assets.upload', '(file, visibility, metadata, onProgress) → (file, { visibility, metadata, onProgress }); returns { file }'),
  uploadRawFile: e('assets.upload', '(file, visibility, metadata) → (file, { visibility, metadata }); returns { file }'),
  assetLink: e('assets.link', '(fileId, app, entityType, entityId, visibility, webhookUrl) → (fileId, { app, entityType, entityId }, { visibility, webhookUrl })'),
  assetUnlink: e('assets.unlink', '(fileId, app, entityType, entityId) → (fileId, { app, entityType, entityId })'),
  assetGet: e('assets.get'),
  assetGetVariants: e('assets.get', 'variants are on the asset: (await assets.get(id)).variants'),
  assetGetUrl: e('assets.url', 'returns the URL string, not { url }'),
  getFileDownloadUrlAsync: e('assets.url'),
  fetchAssetDownloadUrl: e('assets.url'),
  getFileDownloadUrl: e('assets.publicUrl'),
  getFileDownloadUrls: e('assets.urls'),
  getBatchFileAccess: e('assets.access'),
  getFileContentAsText: e('assets.text'),
  getFileContentAsBlob: e('assets.blob'),
  fetchAssetContent: e(null),
  getAssetUrlCacheTTL: e(null),
  assetRestore: e('assets.restore'),
  assetDelete: e('assets.delete', '(fileId, force) → (fileId, { force })'),
  deleteFile: e('assets.delete'),
  assetUpdateVisibility: e('assets.setVisibility'),
  listUserFiles: e('assets.list', '(limit, offset) → ({ limit, offset })'),
  getAccountStorageUsage: e('assets.usage'),
  uploadAvatar: e('assets.uploadAvatar'),
  uploadProfileBanner: e(null),
  getServiceAssetMetadataByIds: e('server:assets.metadataByIds'),
  getServiceAssetMetadataBySha256: e('server:assets.metadataBySha256'),
  getServiceLinkedDownloadUrls: e('server:assets.linkedDownloadUrls'),

  // ── identity: DID, keys, identity links, domains, backup, export ────────
  resolveDid: e('identity.resolveDid'),
  getMyDid: e('identity.did', 'now a getter'),
  getMyDidDocument: e(null),
  listAuthMethods: e('identity.authMethods'),
  getIdentityRootStatus: e('identity.rootStatus'),
  createIdentityLink: e('identity.links.create'),
  getIdentityLink: e('identity.links.get'),
  signIdentityLink: e('identity.links.sign'),
  completeIdentityLinkWithEmailCode: e('identity.links.complete'),
  cancelIdentityLink: e('identity.links.cancel'),
  getIdentityLinkAssertionOptions: e(null),
  completeIdentityLink: e(null),
  removePasskey: e(null, 'passkeys are removed (ADR 0030)'),
  rotateKey: e('identity.rotateKey'),
  signRecord: e(null),
  publishRecord: e(null),
  getRecord: e(null),
  verifyRecord: e(null),
  exportMyData: e('identity.export'),
  requestDomainVerification: e('identity.domains.requestVerification'),
  verifyDomain: e('identity.domains.verify'),
  listDomains: e('identity.domains.list'),
  removeDomain: e('identity.domains.remove'),
  createEncryptedBackup: e('identity.backup.create'),
  getBackupStatus: e('identity.backup.status'),
  deleteBackup: e('identity.backup.delete'),
  restoreFromEncryptedBackup: e('identity.backup.restore'),

  // ── accounts (the account graph) ────────────────────────────────────────
  listAccounts: e('accounts.list'),
  getAccount: e('accounts.get'),
  switchToAccount: e('accounts.actAs'),
  createAccount: e('accounts.create'),
  updateAccount: e('accounts.update'),
  archiveAccount: e('accounts.archive'),
  listAccountMembers: e('accounts.members.list'),
  inviteAccountMember: e('accounts.members.invite'),
  updateAccountMember: e('accounts.members.update'),
  removeAccountMember: e('accounts.members.remove'),
  transferAccountOwnership: e('accounts.transferOwnership'),
  listChildAccounts: e(null),
  provisionChannelAccount: e(null),
  provisionChannelMember: e(null),
  revokeChannelMember: e(null),

  // ── apps: applications an account owns, and the ones a user granted ─────
  listAccountApps: e('apps.list'),
  createApp: e('apps.create'),
  getApp: e('apps.get'),
  updateApp: e('apps.update'),
  deleteApp: e('apps.delete'),
  getAppUsage: e('apps.usage'),
  listAppCredentials: e('apps.credentials.list'),
  createAppCredential: e('apps.credentials.create'),
  rotateAppCredential: e('apps.credentials.rotate'),
  revokeAppCredential: e('apps.credentials.revoke'),
  getPublicApplication: e('apps.getPublic'),
  listConnectedApps: e('apps.connected.list'),
  revokeAppGrant: e('apps.connected.revoke'),
  listConnectedMcpClients: e('apps.connected.mcpClients'),
  revokeConnectedMcpClient: e('apps.connected.revokeMcpClient'),

  // ── linked external accounts (Mastodon, Bluesky) ────────────────────────
  startLinkedAccount: e('linkedAccounts.start'),
  completeLinkedAccount: e('linkedAccounts.complete'),
  listLinkedAccounts: e('linkedAccounts.list'),
  revokeLinkedAccount: e('linkedAccounts.revoke'),
  getLinkedAccountsForUser: e('server:linkedAccounts.forUser'),

  // ── agency (delegated capabilities) ─────────────────────────────────────
  listAvailableCapabilityCatalogs: e('agency.catalogs'),
  listDelegationGrants: e('agency.grants.list'),
  createDelegationGrant: e('agency.grants.create'),
  updateDelegationGrant: e('agency.grants.update'),
  revokeDelegationGrant: e('agency.grants.revoke'),
  listAccountCapabilityPolicies: e('agency.policies.list'),
  putAccountCapabilityPolicy: e('agency.policies.put'),
  deleteAccountCapabilityPolicy: e('agency.policies.delete'),
  listCapabilityExecutionAuthorizations: e('agency.authorizations.list'),
  revokeCapabilityExecutionAuthorization: e('agency.authorizations.revoke'),
  listCapabilityAuditEvents: e('agency.auditEvents'),
  mintRequesterAssertion: e('server:agency.mintRequesterAssertion'),
  introspectRequesterAssertion: e('server:agency.introspectRequesterAssertion'),

  // ── store ────────────────────────────────────────────────────────────────
  listStoreCategories: e('store.categories'),
  listStoreApps: e('store.apps'),
  getStoreApp: e('store.app'),
  listStoreReviews: e('store.reviews.list'),
  getMyStoreReview: e('store.reviews.mine'),
  writeStoreReview: e('store.reviews.write'),
  deleteMyStoreReview: e('store.reviews.deleteMine'),
  replyToStoreReview: e(null),
  deleteStoreReviewReply: e(null),
  getAppListing: e('store.listing.get'),
  writeAppListing: e('store.listing.write'),
  submitAppListing: e('store.listing.submit'),
  unpublishAppListing: e('store.listing.unpublish'),
  listAppListingScreenshots: e('store.listing.screenshots.list'),
  addAppListingScreenshot: e('store.listing.screenshots.add'),
  updateAppListingScreenshot: e('store.listing.screenshots.update'),
  deleteAppListingScreenshot: e('store.listing.screenshots.delete'),
  reorderAppListingScreenshots: e('store.listing.screenshots.reorder'),

  // ── billing ──────────────────────────────────────────────────────────────
  getUserPayments: e('billing.payments'),
  getSubscription: e('billing.subscription'),
  getCurrentUserSubscription: e('billing.subscription'),
  getWallet: e('billing.wallet'),
  getCurrentUserWallet: e('billing.wallet'),
  getWalletTransactions: e('billing.walletTransactions', '(userId, options) → ({ userId, ...options })'),
  getCurrentUserWalletTransactions: e('billing.walletTransactions', '(options) → (options)'),
  createPayment: e(null),
  getPayment: e(null),

  // ── reputation (read-only for users; awards come from apps) ─────────────
  getReputationBalance: e('reputation.balance'),
  getMyReputationBalance: e('reputation.balance', 'no userId = mine'),
  getReputationLeaderboard: e('reputation.leaderboard', '(limit, offset) → ({ limit, offset })'),
  getReputationRules: e('reputation.rules'),
  getReputationTransactions: e('reputation.transactions', '(userId, limit, offset) → (userId, { limit, offset })'),
  getReputationInfluence: e('reputation.influence'),
  awardReputation: e('server:reputation.award'),
  createReputationDispute: e(null),
  getUserReputationDisputes: e(null),
  upsertReputationRule: e(null),
  reverseReputationTransaction: e(null),
  voidReputationTransaction: e(null),
  recalculateReputation: e(null),
  getReputationDisputeQueue: e(null),
  resolveReputationDispute: e(null),

  // ── civic ────────────────────────────────────────────────────────────────
  getPublicCard: e('civic.publicCard'),
  getMyIdPayload: e('civic.idPayload'),
  buildAttestQrPayload: e('civic.buildAttestQrPayload'),
  submitRealLifeAttestation: e('civic.attest'),
  getValidatorInbox: e('civic.validation.inbox'),
  submitValidationVote: e('civic.validation.vote'),
  denyValidation: e('civic.validation.deny'),
  vouchForPerson: e('civic.vouch'),
  withdrawVouch: e('civic.withdrawVouch'),
  getPersonhood: e('civic.personhood'),
  getMyPersonhood: e('civic.personhood', 'no userId = mine'),
  issueCredential: e('civic.credentials.issue'),
  listCredentials: e('civic.credentials.list'),
  listMyCredentials: e('civic.credentials.list', '(opts) → (undefined, opts)'),
  verifyCredential: e('civic.credentials.verify'),
  revokeCredential: e('civic.credentials.revoke'),

  // ── nodes ────────────────────────────────────────────────────────────────
  registerNode: e('nodes.register'),
  getMyNode: e('nodes.mine'),
  removeMyNode: e('nodes.removeMine'),
  provisionManagedVault: e('nodes.provisionManagedVault'),
  notifyNodeIngest: e('nodes.notifyIngest'),

  // ── devices: this user's devices, their sessions, and device sign-in ────
  getUserDevices: e('devices.list'),
  removeDevice: e('devices.remove'),
  getDeviceSessions: e('devices.sessions'),
  logoutAllDeviceSessions: e('devices.logoutAll'),
  updateDeviceName: e('devices.rename'),
  getSecurityInfo: e('devices.securityInfo'),
  getSecurityActivity: e('devices.securityActivity'),
  getRecentSecurityActivity: e('devices.securityActivity', '(limit) → (limit, 0); returns the page, read .data'),
  logPrivateKeyExported: e('devices.logPrivateKeyExported'),
  logBackupCreated: e('devices.logBackupCreated'),
  mintFromDeviceSecret: e('devices.mintToken'),
  registerBrowserDevice: e('devices.registerBrowser'),
  requestDeviceJoinCode: e('devices.requestJoinCode'),
  joinBrowserDevice: e('devices.joinBrowser'),
  provisionBackgroundCredential: e('devices.provisionBackgroundCredential'),
  registerDevice: e(null),

  // ── small surfaces ───────────────────────────────────────────────────────
  listTopics: e('topics.list'),
  searchTopics: e('topics.search'),
  getTopicBySlug: e('topics.get'),
  getTopicCategories: e('topics.categories'),
  resolveTopicNames: e('topics.resolveNames'),
  updateTopicMetadata: e('topics.update'),
  getAppData: e('appData.get'),
  setAppData: e('appData.set'),
  deleteAppData: e('appData.delete'),
  listAppData: e('appData.list'),
  discoverContacts: e('contacts.discover'),
  inference: e(null, "createInferenceClient(oxy) from '@oxy.so/core/inference'"),

  // ── language: plain helpers, not client methods ─────────────────────────
  getStorage: e(null),
  getCurrentLanguage: e(null, 'use getLanguageCode / the i18n helpers'),
  getCurrentLanguageMetadata: e(null),
  getCurrentLanguageName: e(null),
  getCurrentNativeLanguageName: e(null),

  // ── removed: no route behind them (features.ts, location, analytics, chains)
  submitFeedback: e(null),
  getSubscriptionPlans: e(null),
  getIndividualFeatures: e(null),
  subscribe: e(null),
  subscribeToFeature: e(null),
  cancelSubscription: e(null),
  reactivateSubscription: e(null),
  getCurrentSubscription: e(null),
  getSavedItems: e(null),
  getCollections: e(null),
  saveItem: e(null),
  removeSavedItem: e(null),
  createCollection: e(null),
  deleteCollection: e(null),
  getUserHistory: e(null),
  clearUserHistory: e(null),
  deleteHistoryItem: e(null),
  getFAQs: e(null),
  searchFAQs: e(null),
  getUserAchievements: e(null),
  getAllAchievements: e(null),
  updateLocation: e(null),
  getNearbyUsers: e(null),
  trackEvent: e(null),
  getAnalytics: e(null),
  appendChainRecord: e(null),
  readChainRecords: e(null),

  // ── server (OxyServer, `@oxy.so/core/server`) ───────────────────────────
  configureServiceAuth: e('server:configureServiceAuth'),
  getServiceToken: e('server:serviceToken'),
  invalidateServiceToken: e('server:invalidateServiceToken'),
  makeServiceRequest: e('server:serviceRequest'),
  verifyServiceActingAs: e('server:verifyActingAs'),
  verifyAccountEvent: e('server:accountEvents.verify'),
  listAccountEvents: e('server:accountEvents.list'),
  auth: e('server:middleware.auth'),
  authSocket: e('server:middleware.socket'),
  serviceAuth: e('server:middleware.service'),
  requireScope: e('server:middleware.requireScope'),
};
