/**
 * Hook that generates an opt-in daily AI brief from non-content email counts.
 *
 * Streams the response for a typing effect and caches the result
 * so it's not regenerated on every screen visit.
 */

import { useState, useRef, useCallback, useEffect, useMemo } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useOxy } from '@oxyhq/services';
import { streamAliaChatCompletion, type AliaMessage } from '@/services/aliaApi';
import { aiKeys } from '@/hooks/queries/queryKeys';
import type { Message } from '@/services/emailApi';

const BRIEF_CACHE_TTL = 30 * 60 * 1000; // 30 minutes
const SYSTEM_PROMPT = `You are Alia, an AI email assistant built into the Inbox app.

Generate a concise daily brief (2-4 sentences) using only aggregate inbox counts. Do not claim to know sender names, subject lines, message contents, deadlines, or action items because those private details are not provided. Be warm but efficient — no greetings, no sign-offs, just the brief. Write in second person ("You have...").`;

function buildPrompt(messages: Message[]): AliaMessage[] {
  const unreadCount = messages.filter((m) => !m.flags.seen).length;
  const starredCount = messages.filter((m) => m.flags.starred).length;
  const attachmentCount = messages.filter((m) => m.attachments.length > 0).length;

  const userMessage = `Recent inbox counts: ${messages.length} total emails, ${unreadCount} unread, ${starredCount} starred, ${attachmentCount} with attachments. Write a brief daily summary for this inbox using only these aggregate counts.`;

  return [
    { role: 'system' as const, content: SYSTEM_PROMPT },
    { role: 'user' as const, content: userMessage },
  ];
}

interface UseDailyBriefOptions {
  /** When false, the hook does no work — used to honor the `aiBrief` pref. */
  enabled?: boolean;
}

export function useDailyBrief(messages: Message[], options: UseDailyBriefOptions = {}) {
  const { enabled = true } = options;
  const queryClient = useQueryClient();
  const { oxyServices, user } = useOxy();

  // The day is re-read every render so the key self-heals when midnight passes
  // with the app open, but the key ARRAY must keep a stable identity: it feeds
  // `generate` and both effects below, and a fresh array per render would make
  // every one of them re-run on every render.
  const day = new Date().toISOString().slice(0, 10);
  const cacheKey = useMemo(() => aiKeys.dailyBrief(day), [day]);

  // Only the id matters for "is somebody signed in"; depending on the `user`
  // object would re-run the effects whenever the SDK hands back a new instance.
  const userId = user?.id ?? null;

  const [briefText, setBriefText] = useState('');

  // One controller per generation run. Aborting it cancels the HTTP request
  // itself; the previous boolean flag only stopped *consuming* the stream while
  // the download kept running.
  const runControllerRef = useRef<AbortController | null>(null);
  const unmountedRef = useRef(false);

  // One auto-generation attempt per day key. Without it the brief stays empty
  // until something calls `generate` — the cache read below only helps once a
  // brief already exists. Released again in `onError` so a failed attempt is
  // not permanent.
  const autoGeneratedForRef = useRef<string | null>(null);

  // Check cache on mount / day rollover (skip when the feature is disabled).
  useEffect(() => {
    if (!enabled) return;
    const cached = queryClient.getQueryData<string>(cacheKey);
    if (cached) {
      setBriefText(cached);
    }
  }, [enabled, cacheKey, queryClient]);

  // The generation is a mutation (a one-shot side-effecting stream) rather than
  // a query: it writes its result into the query cache keyed by day so it isn't
  // regenerated on every screen visit, while streaming chunks into local state
  // for the typewriter effect.
  const generateMutation = useMutation<string, Error, void>({
    mutationKey: cacheKey,
    // One shot per call. The brief is an expensive, non-critical LLM request;
    // the client-wide `mutations.retry: 1` default just doubles the load on a
    // failing endpoint. Recovery is owned by the auto-generation effect below,
    // which releases its guard on failure and retries when the inputs change.
    retry: false,
    mutationFn: async () => {
      const controller = new AbortController();
      // `mutate()` is fire-and-forget, so this body can start after the
      // component has already gone away. Start pre-aborted in that case rather
      // than opening a request nobody will read.
      if (unmountedRef.current) controller.abort();
      runControllerRef.current?.abort();
      runControllerRef.current = controller;

      const prompt = buildPrompt(messages);
      let accumulated = '';
      let pendingFrame: number | null = null;

      for await (const delta of streamAliaChatCompletion(
        oxyServices.httpService,
        {
          model: 'alia-lite',
          messages: prompt,
          maxTokens: 300,
          temperature: 0.7,
        },
        controller.signal,
      )) {
        accumulated += delta;
        // One commit per frame, not one per token. A 300-token brief would
        // otherwise be 300 re-renders of a list header, each a candidate
        // re-measure of the header the list pads itself against.
        if (pendingFrame === null) {
          pendingFrame = requestAnimationFrame(() => {
            pendingFrame = null;
            setBriefText(accumulated);
          });
        }
      }

      if (pendingFrame !== null) {
        cancelAnimationFrame(pendingFrame);
        pendingFrame = null;
      }
      setBriefText(accumulated);

      // An empty completion is a failure, not a result. Caching '' poisons the
      // day's slot — it reads back as a cache miss, so the text never appears,
      // while the mutation reports success and the UI sits on its "preparing"
      // copy forever with no error to explain it.
      if (!accumulated) {
        throw new Error('Alia returned an empty brief');
      }

      // Defaults must be registered BEFORE the entry is built: `setQueryData`
      // snapshots the options at build time, so setting them afterwards leaves
      // the entry on the client default gcTime and it is collected minutes
      // later — this query has no observers to keep it alive.
      queryClient.setQueryDefaults(cacheKey, {
        staleTime: BRIEF_CACHE_TTL,
        gcTime: BRIEF_CACHE_TTL,
      });
      queryClient.setQueryData(cacheKey, accumulated, { updatedAt: Date.now() });

      return accumulated;
    },
    onError: () => {
      // The guard STAYS claimed on failure. Releasing it looks like a kindness
      // — "let a later render try again" — but the effect re-runs whenever the
      // day's message count changes, which it does repeatedly while pages load.
      // Against a failing endpoint (a 500 from an unconfigured Alia key, say)
      // that turns one failed brief into a burst of requests. One attempt per
      // day per mount; `regenerate` is the deliberate way to ask for another.
    },
  });

  const { mutate: runGenerate } = generateMutation;

  const generate = useCallback(() => {
    if (!enabled || messages.length === 0 || !userId) return;

    // Serve from cache if present — avoids a redundant AI round-trip.
    const cached = queryClient.getQueryData<string>(cacheKey);
    if (cached) {
      setBriefText(cached);
      return;
    }

    setBriefText('');
    runGenerate();
  }, [enabled, messages.length, userId, queryClient, cacheKey, runGenerate]);

  // Generate on first sight of the day's messages. Guarded by a per-day ref so
  // a single render pass cannot fire twice; `onError` clears it so a failed
  // attempt is retried the next time the inputs actually change.
  useEffect(() => {
    if (!enabled || messages.length === 0 || !userId) return;
    if (autoGeneratedForRef.current === day) return;
    autoGeneratedForRef.current = day;
    generate();
  }, [enabled, messages.length, userId, day, generate]);

  // Cancel the in-flight request on unmount, and remember that we are gone so a
  // run that starts afterwards does not open a fresh one.
  useEffect(() => {
    unmountedRef.current = false;
    return () => {
      unmountedRef.current = true;
      runControllerRef.current?.abort();
    };
  }, []);

  const regenerate = useCallback(() => {
    queryClient.removeQueries({ queryKey: cacheKey });
    // This IS today's attempt, so claim the guard rather than clearing it —
    // otherwise the auto-generation effect would fire a second, duplicate run
    // the next time one of its dependencies changed.
    autoGeneratedForRef.current = day;
    setBriefText('');
    generate();
  }, [generate, queryClient, cacheKey, day]);

  return {
    briefText,
    isStreaming: generateMutation.isPending,
    isLoading: generateMutation.isPending && briefText.length === 0,
    error: generateMutation.error,
    generate,
    regenerate,
  };
}
