/**
 * `users` behaviour, against a REAL Postgres.
 *
 * One `describe` per decision in `users.ts` that a comment alone would not keep
 * true. Everything here runs through the application's own pool against the
 * throwaway database `jest.globalSetup.ts` migrated, so what passes is what the
 * shipped DDL does — there is no mock and no second migrator.
 *
 * Every row carries a per-test random id and identifiers, so no assertion
 * depends on the table being empty.
 */

import { randomUUID } from 'node:crypto';
import { eq, sql } from 'drizzle-orm';
import { closePostgres, connectPostgres, getDb } from '../../../config/postgres';
import { maybeHashEmail, maybeHashPhone } from '../../../utils/contactHash';
import {
  ACCOUNT_KINDS,
  ACCOUNT_STATUSES,
  USER_COLOR_PRESETS,
  randomUserColor,
  users,
} from '../users';

/** Postgres `unique_violation`. */
const UNIQUE_VIOLATION = '23505';
/** Postgres `check_violation`. */
const CHECK_VIOLATION = '23514';
/** Postgres `generated_always`. */
const GENERATED_ALWAYS = '428C9';

/** A distinct identifier per test, so parallel suites cannot collide. */
const unique = () => randomUUID().replace(/-/g, '');

/**
 * The SQLSTATE a driver error carries.
 *
 * Drizzle wraps a driver failure in its own error, so the code lives on the
 * `cause` — walking the chain is what makes an assertion mean "the constraint
 * fired" rather than "something threw".
 */
function pgErrorCode(error: unknown): string | undefined {
  for (let current = error; current instanceof Error; current = current.cause) {
    const code: unknown = Reflect.get(current, 'code');
    if (typeof code === 'string') return code;
  }
  return undefined;
}

/** Await a query expecting rejection, returning the error. Runs it exactly once. */
async function rejection(query: Promise<unknown>): Promise<unknown> {
  try {
    await query;
  } catch (error) {
    return error;
  }
  throw new Error('Expected the query to be rejected by a constraint, but it succeeded.');
}

/** Insert a minimal valid user and return its id. */
async function insertUser(
  values: Partial<typeof users.$inferInsert> = {}
): Promise<string> {
  const [row] = await getDb()
    .insert(users)
    .values({ color: 'teal', ...values })
    .returning({ id: users.id });
  return row.id;
}

/** The two generated hash columns of one row. */
async function contactHashes(
  id: string
): Promise<{ hashedEmail: string | null; hashedPhone: string | null }> {
  const [row] = await getDb()
    .select({ hashedEmail: users.hashedEmail, hashedPhone: users.hashedPhone })
    .from(users)
    .where(eq(users.id, id));
  return row;
}

beforeAll(async () => {
  await connectPostgres();
});

afterAll(async () => {
  await closePostgres();
});

describe('contact hashes are generated by the database', () => {
  /**
   * Inputs the JS canonicalization and the SQL one must agree on byte for byte.
   *
   * Deliberately covers the messy shapes: surrounding whitespace, mixed case,
   * multibyte UTF-8, a literal backslash (the reason the SQL expression doubles
   * backslashes before `decode(…, 'escape')`), and octal-looking text.
   *
   * KNOWN BOUNDARY, not covered: codepoints whose Unicode full case mapping
   * differs from `lower()`'s simple one — U+0130 `İ` is the classic. JS
   * `toLowerCase()` expands it to `i` + U+0307; `lower()` does not. An email
   * local part containing one would hash differently on the client and in the
   * database. Non-ASCII local parts are vanishingly rare (SMTPUTF8 is barely
   * deployed and most providers reject them), and the alternative — hashing in
   * application code — reintroduces exactly the bypassable hook this replaces.
   */
  // `{u}` is replaced with a random token INSIDE the local part, so each row is
  // unique under `lower(btrim(email))` without disturbing the surrounding
  // whitespace and casing each case exists to exercise.
  const emails = [
    '{u}@oxy.so',
    '  Na{u}te@Oxy.SO  ',
    'héllo{u}@example.com',
    'a\\b{u}@example.com',
    'a\\123b{u}@example.com',
    '"weird\\ local {u}"@example.com',
    '€uro{u}@example.com',
  ];

  const phones = [
    '+34600112233',
    ' +34 600-11 22 33 ',
    '34600112233',
    '(555) 010-9999',
  ];

  it.each(emails)('matches maybeHashEmail for %j', async (template) => {
    const email = template.replace('{u}', unique());
    const id = await insertUser({ email });
    const { hashedEmail } = await contactHashes(id);

    expect(hashedEmail).toBe(maybeHashEmail(email));
    expect(hashedEmail).toMatch(/^[0-9a-f]{64}$/);
  });

  it.each(phones)('matches maybeHashPhone for %j', async (phone) => {
    const id = await insertUser({ phone });
    const { hashedPhone } = await contactHashes(id);

    expect(hashedPhone).toBe(maybeHashPhone(phone));
    expect(hashedPhone).toMatch(/^[0-9a-f]{64}$/);
  });

  it('hashes an absent or blank value to NULL, as maybeHash* returns undefined', async () => {
    const absent = await contactHashes(await insertUser());
    expect(absent.hashedEmail).toBeNull();
    expect(absent.hashedPhone).toBeNull();

    const blank = await contactHashes(await insertUser({ email: '   ', phone: 'no digits' }));
    expect(blank.hashedEmail).toBeNull();
    expect(maybeHashEmail('   ')).toBeUndefined();
    expect(blank.hashedPhone).toBeNull();
    expect(maybeHashPhone('no digits')).toBeUndefined();
  });

  it('recomputes on UPDATE — the failure mode the Mongoose hook existed for', async () => {
    const id = await insertUser({ email: `first-${unique()}@oxy.so` });
    const before = await contactHashes(id);

    const next = `second-${unique()}@oxy.so`;
    await getDb().update(users).set({ email: next }).where(eq(users.id, id));

    const after = await contactHashes(id);
    expect(after.hashedEmail).not.toBe(before.hashedEmail);
    expect(after.hashedEmail).toBe(maybeHashEmail(next));
  });

  it('cannot be written directly — not by a route, a backfill, or psql', async () => {
    // Raw SQL on purpose: the drizzle types already refuse this at compile time,
    // so only a hand-written statement can reach the database's own refusal —
    // which is precisely who the guarantee is for.
    const error = await rejection(
      getDb().execute(sql`
        insert into users (id, color, email, hashed_email)
        values (${unique()}, 'teal', ${`x-${unique()}@oxy.so`}, ${'0'.repeat(64)})
      `)
    );

    expect(pgErrorCode(error)).toBe(GENERATED_ALWAYS);
  });
});

describe('identity uniqueness is trimmed and case-insensitive', () => {
  it.each([
    ['username', (value: string): Partial<typeof users.$inferInsert> => ({ username: value })],
    ['email', (value: string): Partial<typeof users.$inferInsert> => ({ email: value })],
    ['publicKey', (value: string): Partial<typeof users.$inferInsert> => ({ publicKey: value })],
  ])('rejects a %s differing only by case or surrounding space', async (field, build) => {
    // The padding wraps the WHOLE value — `btrim` only sees the ends, so
    // `Ident  @oxy.so` would be a genuinely different address, not a collision.
    const value = field === 'email' ? `ident${unique()}@oxy.so` : `Ident${unique()}`;
    await insertUser(build(value));

    const error = await rejection(
      getDb()
        .insert(users)
        .values({ color: 'teal', ...build(`  ${value.toUpperCase()}  `) })
    );

    expect(pgErrorCode(error)).toBe(UNIQUE_VIOLATION);
  });

  it('treats NULL identifiers as distinct — many accounts carry none', async () => {
    await expect(
      getDb()
        .insert(users)
        .values([{ color: 'teal' }, { color: 'blue' }])
    ).resolves.toBeDefined();
  });

  it('is the index a lookup must use — `lower(btrim(username))`, not `username`', async () => {
    const username = `Lookup${unique()}`;
    await insertUser({ username });

    const found = await getDb()
      .select({ id: users.id })
      .from(users)
      .where(sql`lower(btrim(${users.username})) = lower(btrim(${` ${username.toUpperCase()} `}))`);

    expect(found).toHaveLength(1);
  });
});

describe('closed value sets and value constraints', () => {
  it('accepts every named color preset and a legacy hex, in any case', async () => {
    for (const color of USER_COLOR_PRESETS) {
      await expect(insertUser({ color })).resolves.toEqual(expect.any(String));
    }
    await expect(insertUser({ color: '#abc' })).resolves.toEqual(expect.any(String));
    await expect(insertUser({ color: '#ABCDEF' })).resolves.toEqual(expect.any(String));
  });

  it('rejects a color that is neither a preset nor a hex', async () => {
    const error = await rejection(
      getDb().execute(sql`
        insert into users (id, color) values (${unique()}, 'chartreuse')
      `)
    );
    expect(pgErrorCode(error)).toBe(CHECK_VIOLATION);
  });

  it('accepts the four inactivity windows and NULL, and nothing else', async () => {
    for (const days of [30, 90, 180, 365]) {
      await expect(
        insertUser({ accountExpiresAfterInactivityDays: days })
      ).resolves.toEqual(expect.any(String));
    }
    await expect(
      insertUser({ accountExpiresAfterInactivityDays: null })
    ).resolves.toEqual(expect.any(String));

    const error = await rejection(
      insertUser({ accountExpiresAfterInactivityDays: 45 })
    );
    expect(pgErrorCode(error)).toBe(CHECK_VIOLATION);
  });

  it.each([
    ['kind', 'chapter'],
    ['account_status', 'suspended'],
    ['type', 'daemon'],
    ['reputation_tier', 'legendary'],
    ['preference_theme', 'sepia'],
    ['organization_category', 'syndicate'],
  ])('rejects an undeclared %s from a raw write', async (column, value) => {
    // Raw SQL on purpose: the typed column refuses this at compile time, so
    // only a hand-written statement (backfill, psql) can reach the constraint —
    // which is exactly who it has to stop.
    const error = await rejection(
      getDb().execute(sql`
        insert into users (id, color, ${sql.raw(column)})
        values (${unique()}, 'teal', ${value})
      `)
    );
    expect(pgErrorCode(error)).toBe(CHECK_VIOLATION);
  });

  it.each([
    ['kind', 'organization'],
    ['account_status', 'archived'],
    ['type', 'federated'],
    ['reputation_tier', 'high_trust'],
    ['preference_theme', 'dark'],
    ['organization_category', 'cooperative'],
  ])('accepts a declared %s (guards against a check that rejects everything)', async (column, value) => {
    await expect(
      getDb().execute(sql`
        insert into users (id, color, ${sql.raw(column)})
        values (${unique()}, 'teal', ${value})
      `)
    ).resolves.toBeDefined();
  });
});

describe('theme preference is whole or absent', () => {
  it('accepts both halves together', async () => {
    const id = await insertUser({
      themePreferenceMode: 'dark',
      themePreferenceColorPreset: 'oxy',
    });
    const [row] = await getDb()
      .select({
        mode: users.themePreferenceMode,
        preset: users.themePreferenceColorPreset,
      })
      .from(users)
      .where(eq(users.id, id));

    expect(row).toEqual({ mode: 'dark', preset: 'oxy' });
  });

  it('accepts neither — the absence consumers fall back on', async () => {
    const id = await insertUser();
    const [row] = await getDb()
      .select({ mode: users.themePreferenceMode })
      .from(users)
      .where(eq(users.id, id));

    expect(row.mode).toBeNull();
  });

  it('rejects half a preference, which Mongo allowed and the serializer discarded', async () => {
    const modeOnly = await rejection(insertUser({ themePreferenceMode: 'dark' }));
    expect(pgErrorCode(modeOnly)).toBe(CHECK_VIOLATION);

    const emptyPreset = await rejection(
      insertUser({ themePreferenceMode: 'dark', themePreferenceColorPreset: '' })
    );
    expect(pgErrorCode(emptyPreset)).toBe(CHECK_VIOLATION);
  });
});

describe('defaults', () => {
  it('applies the Mongoose defaults a new account relied on', async () => {
    const id = await insertUser();
    // Columns named one by one rather than a bare `select()`: `autoForwardKeepCopy`
    // is a PROTECTED column, and naming it is the sanctioned way to read one.
    const [row] = await getDb()
      .select({
        kind: users.kind,
        accountStatus: users.accountStatus,
        type: users.type,
        verified: users.verified,
        reputationTier: users.reputationTier,
        reputationRankWeight: users.reputationRankWeight,
        isStaff: users.isStaff,
        isSeedVerifier: users.isSeedVerifier,
        isSensitive: users.isSensitive,
        languages: users.languages,
        privacyDiscoverableByEmail: users.privacyDiscoverableByEmail,
        privacyDiscoverableByPhone: users.privacyDiscoverableByPhone,
        privacyProfileVisibility: users.privacyProfileVisibility,
        privacyIsPrivateAccount: users.privacyIsPrivateAccount,
        notificationPushEnabled: users.notificationPushEnabled,
        notificationMarketingEmails: users.notificationMarketingEmails,
        preferenceTheme: users.preferenceTheme,
        autoForwardKeepCopy: users.autoForwardKeepCopy,
      })
      .from(users)
      .where(eq(users.id, id));

    expect(row.kind).toBe('personal');
    expect(row.accountStatus).toBe('active');
    expect(row.type).toBe('local');
    expect(row.verified).toBe(false);
    expect(row.reputationTier).toBe('new');
    expect(row.reputationRankWeight).toBe(0.1);
    expect(row.isStaff).toBe(false);
    expect(row.isSeedVerifier).toBe(false);
    expect(row.isSensitive).toBe(false);
    expect(row.languages).toEqual(['en-US']);
    // Contact discovery is opt-IN; the rest of the privacy defaults are on or
    // off exactly as the Mongoose schema declared them.
    expect(row.privacyDiscoverableByEmail).toBe(false);
    expect(row.privacyDiscoverableByPhone).toBe(false);
    expect(row.privacyProfileVisibility).toBe(true);
    expect(row.privacyIsPrivateAccount).toBe(false);
    expect(row.notificationPushEnabled).toBe(true);
    expect(row.notificationMarketingEmails).toBe(false);
    expect(row.preferenceTheme).toBe('system');
    expect(row.autoForwardKeepCopy).toBe(true);
  });

  it('picks a random non-premium color when none is supplied', async () => {
    const [row] = await getDb().insert(users).values({}).returning({ color: users.color });

    expect(USER_COLOR_PRESETS).toContain(row.color);
    expect(row.color).not.toBe('oxy');
    // The generator itself, sampled — a single insert could pass by luck.
    const sampled = new Set(Array.from({ length: 200 }, () => randomUserColor()));
    expect(sampled.has('oxy')).toBe(false);
    expect(sampled.size).toBeGreaterThan(1);
  });

  it('stores an ObjectId hex verbatim and mints uuid v7 otherwise', async () => {
    const legacy = 'a1b2c3d4e5f60718293a4b5d';
    await getDb().insert(users).values({ id: legacy, color: 'teal' });
    const [kept] = await getDb()
      .select({ id: users.id })
      .from(users)
      .where(eq(users.id, legacy));
    expect(kept.id).toBe(legacy);

    const minted = await insertUser();
    expect(minted).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/
    );
  });
});
