#!/usr/bin/env bash
# Rebase a branch that adds ONE drizzle migration onto a base that already took
# its index, renumber it to the next free index and prove the result.
#
#   renumber-migration.sh <base-ref> <branch-ref> <migration-tag> <out-branch> [<pg-admin-url>]
#
#   base-ref       what the branch will land on: origin/main at the time, or a
#                  composite rehearsal branch (main + other PRs).
#   branch-ref     the PR branch (e.g. origin/feat/i09-internal-metered).
#   migration-tag  the migration name WITHOUT its number (inference_metered_usage).
#   out-branch     local branch to create with the result (pushed only by hand).
#   pg-admin-url   a Postgres that may CREATE DATABASE (a throwaway local one;
#                  default postgres://oxy:oxy@127.0.0.1:5432/postgres). Never prod.
#
# What it does, in order, failing on the first step that does not hold:
#   1. worktree at <base-ref>; cherry-pick merge-base..<branch-ref>;
#      on a conflict ONLY inside packages/api/drizzle/, keep the base's
#      meta/ and drop the branch's own migration SQL (it is regenerated below).
#   2. free index = (max journal idx on the base) + 1; `drizzle-kit generate
#      --name <tag>` must produce exactly NNNN_<tag>.sql at that index; the
#      original deploy-phase marker line is restored.
#   3. checks: generated DDL == the branch's original DDL (marker excluded);
#      a second generate is a no-op; migration phases + journal order + payload
#      guard scripts pass; 0000..N applies to a fresh database (--phase=all)
#      and `drizzle-kit check` is clean.
# It never pushes, never touches a non-throwaway database, and leaves the
# worktree in place for inspection (path printed at the end).
set -euo pipefail

BASE=${1:?base-ref}; BRANCH=${2:?branch-ref}; TAG=${3:?migration-tag}; OUT=${4:?out-branch}
PGADMIN=${5:-postgres://oxy:oxy@127.0.0.1:5432/postgres}
case "$PGADMIN" in *127.0.0.1*|*localhost*) ;; *) echo "refusing a non-local Postgres: $PGADMIN" >&2; exit 2;; esac

REPO=$(git rev-parse --show-toplevel)
WT=$(mktemp -d "${TMPDIR:-/tmp}/renumber-${TAG}-XXXX")
DRZ=packages/api/drizzle
log(){ printf '\n== %s\n' "$*"; }

log "1. $OUT = $BASE + $(git -C "$REPO" rev-list --count "$(git -C "$REPO" merge-base "$BASE" "$BRANCH")..$BRANCH") commit(s) of $BRANCH"
git -C "$REPO" worktree add -q -b "$OUT" "$WT" "$BASE"
cd "$WT"
ORIG_SQL=$(git ls-tree -r --name-only "$BRANCH" -- "$DRZ" | grep -E "^$DRZ/[0-9]{4}_${TAG}\.sql$")
[ -n "$ORIG_SQL" ] || { echo "no $DRZ/NNNN_${TAG}.sql on $BRANCH" >&2; exit 1; }
git show "$BRANCH:$ORIG_SQL" > "$WT/.orig.sql"
case "$(head -1 "$WT/.orig.sql")" in "-- oxy:deploy-phase="*) ;; *) echo "original has no deploy-phase marker" >&2; exit 1;; esac
# The hand-written header (marker + leading comment lines) is not generated by
# drizzle-kit; it is carried over verbatim.
awk 'f==0 && /^--/ {print; next} {f=1}' "$WT/.orig.sql" > "$WT/.header.sql"

for c in $(git rev-list --reverse "$(git merge-base "$BASE" "$BRANCH")..$BRANCH"); do
  if ! git cherry-pick "$c" >/dev/null 2>&1; then
    others=$(git diff --name-only --diff-filter=U | grep -v "^$DRZ/" || true)
    [ -z "$others" ] || { echo "conflict outside drizzle/ at $c: $others" >&2; exit 1; }
    git checkout HEAD -- "$DRZ/meta"
    git rm -q --cached --ignore-unmatch "$ORIG_SQL"; rm -f "$ORIG_SQL"
    git add "$DRZ/meta"
    GIT_EDITOR=true git cherry-pick --continue >/dev/null
  fi
done
# A pick that did not conflict (base without a collision) still brought the
# branch's SQL, snapshot and journal entry: put drizzle/ back to the base's.
ORIG_NUM=$(basename "$ORIG_SQL" | cut -c1-4)
SNAP="$DRZ/meta/${ORIG_NUM}_snapshot.json"
git rm -q --ignore-unmatch "$ORIG_SQL"
if git cat-file -e "$BASE:$SNAP" 2>/dev/null; then git checkout "$BASE" -- "$SNAP"; else git rm -q --ignore-unmatch "$SNAP"; fi
git checkout "$BASE" -- "$DRZ/meta/_journal.json"
git diff --cached --quiet || git commit -q -m "chore(migrations): drop ${TAG} before renumbering"

NEXT=$(bun -e "const j=require('./$DRZ/meta/_journal.json'); console.log(String(Math.max(...j.entries.map(e=>e.idx))+1).padStart(4,'0'))")
log "2. free index $NEXT"
bun install --frozen-lockfile --minimum-release-age=0 >/dev/null
bunx turbo run build --filter=@oxy.so/api^... >/dev/null
( cd packages/api && DATABASE_URL="${PGADMIN%/*}/postgres" bunx drizzle-kit generate --name "$TAG" >/dev/null )
NEW_SQL="$DRZ/${NEXT}_${TAG}.sql"
[ -f "$NEW_SQL" ] || { echo "drizzle-kit did not write $NEW_SQL:" >&2; git status --short "$DRZ" >&2; exit 1; }
cat "$WT/.header.sql" "$NEW_SQL" > "$NEW_SQL.tmp" && mv "$NEW_SQL.tmp" "$NEW_SQL"

log "3. checks"
if ! diff "$WT/.orig.sql" "$NEW_SQL"; then echo "generated $NEW_SQL differs from $ORIG_SQL" >&2; exit 1; fi
echo "identical to $ORIG_SQL (header and DDL)"
( cd packages/api && DATABASE_URL="${PGADMIN%/*}/postgres" bunx drizzle-kit generate 2>&1 | tail -1 | grep -q "No schema changes" ) || { echo "schema drift after generate" >&2; exit 1; }
echo "second generate: no schema changes"
for s in check-migration-phases check-migration-journal-order check-no-payload-persistence; do bun "scripts/$s.mjs" | tail -1 | cut -c1-160; done
DB="renumber_$(date +%s)"
bun -e "const s=new Bun.SQL('$PGADMIN'); await s.unsafe('create database $DB'); process.exit(0)"
URL="${PGADMIN%/*}/$DB"
( cd packages/api && DATABASE_URL="$URL" bun run src/db/migrate.ts --phase=all 2>&1 | tail -1 | grep -o 'Applied [0-9]* migration(s)' \
  && DATABASE_URL="$URL" bunx drizzle-kit check 2>&1 | tail -1 )

git add "$DRZ"
git commit -q -m "chore(migrations): ${TAG} renumbered to ${NEXT} on top of $(git rev-parse --short "$BASE")"
log "ok: $OUT at $(git rev-parse --short HEAD) in $WT (database $DB)"
