-- oxy:deploy-phase=pre
-- Generated by drizzle-kit; target UNIQUE reordered ahead of its composite FKs.
CREATE TABLE "service_acting_as_authority_epochs" (
	"user_id" text NOT NULL,
	"application_id" text NOT NULL,
	"epoch" bigint DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT date_trunc('milliseconds', now()) NOT NULL,
	CONSTRAINT "service_acting_as_authority_epochs_user_id_application_id_pk" PRIMARY KEY("user_id","application_id"),
	CONSTRAINT "service_acting_as_authority_epochs_nonnegative_check" CHECK ("service_acting_as_authority_epochs"."epoch" >= 0)
);
--> statement-breakpoint
ALTER TABLE "auth_challenges" DROP CONSTRAINT "auth_challenges_purpose_check";--> statement-breakpoint
ALTER TABLE "email_verifications" DROP CONSTRAINT "email_verifications_reauth_action_check";--> statement-breakpoint
ALTER TABLE "user_auth_methods" DROP CONSTRAINT "user_auth_methods_type_check";--> statement-breakpoint
ALTER TABLE "auth_challenges" ADD COLUMN "account_id" text;--> statement-breakpoint
ALTER TABLE "auth_challenges" ADD COLUMN "actor_id" text;--> statement-breakpoint
ALTER TABLE "auth_challenges" ADD COLUMN "binding_digest" text;--> statement-breakpoint
ALTER TABLE "auth_codes" ADD COLUMN "auth_method_id" text;--> statement-breakpoint
ALTER TABLE "auth_codes" ADD COLUMN "auth_method_owner_id" text;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "auth_method_id" text;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "auth_method_owner_id" text;--> statement-breakpoint
ALTER TABLE "user_auth_methods" ADD COLUMN "label" text;--> statement-breakpoint
ALTER TABLE "user_auth_methods" ADD COLUMN "enrolled_by_user_id" text;--> statement-breakpoint
ALTER TABLE "user_auth_methods" ADD COLUMN "enrollment_method" text;--> statement-breakpoint
ALTER TABLE "user_auth_methods" ADD COLUMN "last_used_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "user_auth_methods" ADD COLUMN "revoked_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "service_acting_as_authority_epochs" ADD CONSTRAINT "service_acting_as_authority_epochs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "service_acting_as_authority_epochs" ADD CONSTRAINT "service_acting_as_authority_epochs_application_id_applications_id_fk" FOREIGN KEY ("application_id") REFERENCES "public"."applications"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_challenges" ADD CONSTRAINT "auth_challenges_account_id_users_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_challenges" ADD CONSTRAINT "auth_challenges_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_auth_methods" ADD CONSTRAINT "user_auth_methods_id_user_id_key" UNIQUE("id","user_id");--> statement-breakpoint
ALTER TABLE "auth_codes" ADD CONSTRAINT "auth_codes_auth_method_owner_fk" FOREIGN KEY ("auth_method_id","auth_method_owner_id") REFERENCES "public"."user_auth_methods"("id","user_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_auth_method_owner_fk" FOREIGN KEY ("auth_method_id","auth_method_owner_id") REFERENCES "public"."user_auth_methods"("id","user_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_auth_methods" ADD CONSTRAINT "user_auth_methods_enrolled_by_user_id_users_id_fk" FOREIGN KEY ("enrolled_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "auth_challenges_account_id_idx" ON "auth_challenges" USING btree ("account_id") WHERE "auth_challenges"."account_id" is not null;--> statement-breakpoint
CREATE INDEX "auth_codes_auth_method_id_idx" ON "auth_codes" USING btree ("auth_method_id") WHERE "auth_codes"."auth_method_id" is not null;--> statement-breakpoint
CREATE INDEX "sessions_auth_method_id_idx" ON "sessions" USING btree ("auth_method_id") WHERE "sessions"."auth_method_id" is not null;--> statement-breakpoint
ALTER TABLE "auth_challenges" ADD CONSTRAINT "auth_challenges_agent_binding_check" CHECK ("auth_challenges"."purpose" in ('signin', 'rotate_key') or ("auth_challenges"."account_id" is not null and "auth_challenges"."actor_id" is not null and "auth_challenges"."binding_digest" is not null));--> statement-breakpoint
ALTER TABLE "auth_challenges" ADD CONSTRAINT "auth_challenges_binding_digest_check" CHECK ("auth_challenges"."binding_digest" is null or "auth_challenges"."binding_digest" ~ '^[0-9a-f]{64}$');--> statement-breakpoint
ALTER TABLE "auth_challenges" ADD CONSTRAINT "auth_challenges_purpose_check" CHECK ("auth_challenges"."purpose" in ('signin', 'rotate_key', 'agent_signin', 'agent_enroll', 'agent_rotate', 'agent_recover', 'agent_governance'));--> statement-breakpoint
ALTER TABLE "auth_codes" ADD CONSTRAINT "auth_codes_auth_method_owner_check" CHECK (("auth_codes"."auth_method_id" is null) = ("auth_codes"."auth_method_owner_id" is null) and ("auth_codes"."auth_method_owner_id" is null or "auth_codes"."auth_method_owner_id" = coalesce("auth_codes"."operated_by_user_id", "auth_codes"."user_id")));--> statement-breakpoint
ALTER TABLE "email_verifications" ADD CONSTRAINT "email_verifications_reauth_action_check" CHECK (("email_verifications"."purpose" = 'reauth') = ("email_verifications"."reauth_action" is not null) and ("email_verifications"."reauth_action" is null or "email_verifications"."reauth_action" in ('change_password', 'totp', 'link_commons', 'delete_account', 'credentials_manage')));--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_auth_method_owner_check" CHECK (("sessions"."auth_method_id" is null) = ("sessions"."auth_method_owner_id" is null) and ("sessions"."auth_method_owner_id" is null or "sessions"."auth_method_owner_id" = coalesce("sessions"."operated_by_user_id", "sessions"."user_id")));--> statement-breakpoint
ALTER TABLE "user_auth_methods" ADD CONSTRAINT "user_auth_methods_agent_metadata_check" CHECK ("user_auth_methods"."type" <> 'agent_key' or ("user_auth_methods"."label" is not null and "user_auth_methods"."enrollment_method" is not null));--> statement-breakpoint
ALTER TABLE "user_auth_methods" ADD CONSTRAINT "user_auth_methods_enrollment_method_check" CHECK ("user_auth_methods"."enrollment_method" in ('governor', 'rotation', 'recovery'));--> statement-breakpoint
ALTER TABLE "user_auth_methods" ADD CONSTRAINT "user_auth_methods_type_check" CHECK ("user_auth_methods"."type" in ('identity', 'agent_key'));