import {cancelOwnedPeableSubscription,PEABLE_ONE_READINESS,personalFinalInvoiceSchema} from '../peablePersonalBilling.service';
import type {Peable} from '@peable.to/sdk';
const owned={payerAccountId:'payer',providerSubscriptionId:'sub_test',providerCustomerId:'cus_test',providerPriceId:'price_test',storeId:'store',planId:'one-v1',livemode:false};
const subscription={...owned,status:'active',cancelAtPeriodEnd:false,currentPeriodStart:'2026-10-01T00:00:00Z',currentPeriodEnd:'2026-11-01T00:00:00Z'};
function fixture(){const retrieveSubscription=jest.fn().mockResolvedValue(subscription);const cancelAtPeriodEnd=jest.fn().mockResolvedValue({...subscription,cancelAtPeriodEnd:true});return {client:{billing:{retrieveSubscription,cancelAtPeriodEnd}} as unknown as Pick<Peable,'billing'>,retrieveSubscription,cancelAtPeriodEnd};}
it('verifies payer and exact Peable ownership before cancellation',async()=>{const f=fixture();await expect(cancelOwnedPeableSubscription(f.client,'other',owned)).rejects.toThrow('payer');expect(f.retrieveSubscription).not.toHaveBeenCalled();f.retrieveSubscription.mockResolvedValue({...subscription,storeId:'another'});await expect(cancelOwnedPeableSubscription(f.client,'payer',owned)).rejects.toThrow('ownership');expect(f.cancelAtPeriodEnd).not.toHaveBeenCalled();});
it('schedules existing period with stable replay key and never extends it',async()=>{const f=fixture();expect((await cancelOwnedPeableSubscription(f.client,'payer',owned)).cancelAtPeriodEnd).toBe(true);expect(f.cancelAtPeriodEnd).toHaveBeenCalledWith('sub_test',{idempotencyKey:'oxy-one-cancel:sub_test'});f.cancelAtPeriodEnd.mockResolvedValue({...subscription,cancelAtPeriodEnd:true,currentPeriodEnd:'2026-12-01T00:00:00Z'});await expect(cancelOwnedPeableSubscription(f.client,'payer',owned)).rejects.toThrow('period differs');f.retrieveSubscription.mockResolvedValue({...subscription,cancelAtPeriodEnd:true});f.cancelAtPeriodEnd.mockClear();await cancelOwnedPeableSubscription(f.client,'payer',owned);expect(f.cancelAtPeriodEnd).not.toHaveBeenCalled();});
const invoice={platform:'peable',currency:'USD',grossMinorUnits:2999,netMinorUnits:2500,taxMinorUnits:499,merchantFeeMinorUnits:0,taxTreatment:'inclusive',sellerId:'seller',invoiceIssuerId:'issuer',taxQuoteId:'tax',customerLocationEvidenceId:'location',taxRateEvidenceId:'rate',issuedAt:'2026-10-05T00:00:00Z',expiresAt:'2026-10-05T00:05:00Z'};
it('requires inclusive final invoice evidence without added fees or assumed zero tax',()=>{expect(personalFinalInvoiceSchema.safeParse(invoice).success).toBe(true);for(const changed of [{taxMinorUnits:0},{merchantFeeMinorUnits:1},{grossMinorUnits:3000},{taxQuoteId:undefined},{sellerId:undefined},{expiresAt:invoice.issuedAt}])expect(personalFinalInvoiceSchema.safeParse({...invoice,...changed}).success).toBe(false);expect(personalFinalInvoiceSchema.safeParse({...invoice,faircoinQuote:{id:'fx',amountBaseUnits:'1',quotedAt:invoice.issuedAt,expiresAt:'2026-10-05T00:06:00Z',roundingEvidenceId:'rounding'}}).success).toBe(false);});
it('does not substitute one-off Faircoin for recurring purchase',()=>{expect(PEABLE_ONE_READINESS.platform).toBe('peable');expect(PEABLE_ONE_READINESS.purchase).toBe('unavailable');expect(PEABLE_ONE_READINESS.blockers).toContain('recurring_paid_period_evidence');});

it('rejects invalid provider period snapshots before financial calls',async()=>{const f=fixture();f.retrieveSubscription.mockResolvedValue({...subscription,currentPeriodEnd:'invalid'});await expect(cancelOwnedPeableSubscription(f.client,'payer',owned)).rejects.toThrow('period unavailable');expect(f.cancelAtPeriodEnd).not.toHaveBeenCalled();});
