import test from 'node:test';import assert from 'node:assert/strict';
import {attestExactDeployments,DEPLOYMENTS,readExactFeedEvents,replayConfirmedEvents,requireSettledOperation}from'./canary-reconciliation.mjs';
const model='openai/gpt-oss-120b@observed-2026-09-01';
const attestation=()=>({snapshotId:'synthetic',scopedExecutionContractVersion:'3.6.0',deployments:Object.entries(DEPLOYMENTS).map(([deploymentId,provider])=>({deploymentId,provider,modelReference:model,regions:[]}))});
test('canonical exact attestation keeps missing parameter declaration unknown',async()=>{const a=await attestExactDeployments({attestDeployments:async(ids,o)=>{assert.deepEqual(ids,Object.keys(DEPLOYMENTS));assert.equal(o.scopedExecutionContractVersion,'3.6.0');return attestation();}});assert.equal(a.deployments.length,3);assert(!Object.hasOwn(a.deployments[0],'acceptedParameters'));});
test('attestation refuses missing/duplicate/foreign identities and contract',async()=>{for(const mutate of [a=>a.deployments.pop(),a=>a.deployments[0]=a.deployments[1],a=>a.deployments[0].provider='foreign',a=>a.scopedExecutionContractVersion='old']){const a=attestation();mutate(a);await assert.rejects(attestExactDeployments({attestDeployments:async()=>a}));}});
test('feed reads bounded pages with exact request filtering',async()=>{let calls=0;const out=await readExactFeedEvents({readPage:async(cursor,limit)=>{assert.equal(limit,500);calls++;return calls===1?{attempts:[{requestId:'foreign',position:'1'}],next:'1',caughtUp:false}:{attempts:[{requestId:'owned',attemptIndex:0,position:'2',cost:null}],next:'2',caughtUp:true};}},'owned',null);assert.equal(out.pages,2);assert.equal(out.events.length,1);assert.equal(out.events[0].cost,null);});
test('feed refuses nonadvancing cursor and bounded absence',async()=>{await assert.rejects(readExactFeedEvents({readPage:async()=>({attempts:[],next:'x',caughtUp:false})},'owned','x'),/not_advancing/);await assert.rejects(readExactFeedEvents({readPage:async()=>({attempts:[],caughtUp:true})},'owned',null),/not_in_bounded/);});
function fixture(){const d=Object.keys(DEPLOYMENTS)[0];const before={kind:'i09-exact-operation-observation-v1',intent:'fixture',applicationId:'app',ownerAccountId:'owner',readOnly:true,isolation:'repeatable read',metered:[],attempts:[],money:{fixture:{count:'0',sha256:'0'}}};const row={request_id:'r',application_id:'app',account_id:'owner',application_credential_id:'wl',environment:'production',delegated_user_id:null,status:'settled',outcome:'completed',output_tokens:'2',economic_treatment:'internal_metered',economic_relationship_id:'alia-kaana',economic_policy_version:'oxy-inference-economics/2026-10-03.3',usage_receipt_id:null,requested_model_reference:model,admitted_model_reference:model,admitted_provider:DEPLOYMENTS[d],admitted_deployment_id:d,resolved_model_reference:model,final_authorized_deployment_id:d,final_authorized_provider:DEPLOYMENTS[d],final_authorized_model_reference:model,serving_provider:DEPLOYMENTS[d]};const after={...structuredClone(before),metered:[row],attempts:[{request_id:'r',attempt_index:0,served:true,deployment_id:d,provider:DEPLOYMENTS[d],model_reference:model,facts_digest:'digest',cost_amount:null}]};return{before,after,canary:{ok:true,firstHttpStatus:200,retryHttpStatus:409,clientRequestId:'fixture',requestId:'r',authority:{credentialId:'wl'},usage:[{unit:'output_tokens',quantity:2}],provider:DEPLOYMENTS[d]}};}
test('settled exact operation rejects duplicate key, wrong authority, money changes',()=>{const f=fixture();assert.equal(requireSettledOperation(f.before,f.after,f.canary).request_id,'r');for(const mutate of [f=>f.before.metered.push({}),f=>f.after.metered[0].application_credential_id='other',f=>f.after.money.fixture.count='1']){const f=fixture();mutate(f);assert.throws(()=>requireSettledOperation(f.before,f.after,f.canary));}});
test('replay calls canonical writer once only after exact authenticated facts match',async()=>{const {after}=fixture();let writes=0;const result=await replayConfirmedEvents({events:[{requestId:'r',attemptIndex:0,cost:null}],observation:after,feedModule:{attemptFactsDigest:()=> 'digest',ingestProviderCostAttempts:async()=>{writes++;return{inserted:0,duplicates:1,mismatches:0};}},readAfter:async()=>structuredClone(after)});assert.equal(writes,1);assert.equal(result.duplicates,1);assert.equal(after.attempts[0].cost_amount,null);});
test('foreign or altered feed cannot write, unexpected insert cannot pass',async()=>{const {after}=fixture();let writes=0;const args={events:[{requestId:'foreign',attemptIndex:0}],observation:after,feedModule:{attemptFactsDigest:()=> 'digest',ingestProviderCostAttempts:async()=>{writes++;return{inserted:1,duplicates:0,mismatches:0};}},readAfter:async()=>after};await assert.rejects(replayConfirmedEvents(args),/facts_differ/);assert.equal(writes,0);args.events[0].requestId='r';await assert.rejects(replayConfirmedEvents(args),/not_duplicate_only/);assert.equal(writes,1);});
