import test from 'node:test';
import assert from 'node:assert/strict';
import {DEPLOYMENTS,requireSettledOperation} from './canary-reconciliation.mjs';
const model='openai/gpt-oss-120b@observed-2026-09-01';
function fixture(){
 const deployment=Object.keys(DEPLOYMENTS).find(x=>DEPLOYMENTS[x]==='groq');
 const before={kind:'i09-exact-operation-observation-v1',intent:'fixture',applicationId:'app',ownerAccountId:'owner',readOnly:true,isolation:'repeatable read',metered:[],attempts:[],money:{fixture:{count:'0',sha256:'0'}}};
 const row={request_id:'r',application_id:'app',account_id:'owner',application_credential_id:'wl',environment:'production',delegated_user_id:null,status:'settled',outcome:'completed',output_tokens:'2',economic_treatment:'internal_metered',economic_relationship_id:'alia-kaana',economic_policy_version:'oxy-inference-economics/2026-10-03.3',usage_receipt_id:null,requested_model_reference:model,admitted_model_reference:model,admitted_provider:'groq',admitted_deployment_id:deployment,resolved_model_reference:model,final_authorized_deployment_id:null,final_authorized_provider:null,final_authorized_model_reference:null,serving_provider:'groq'};
 return {before,after:{...structuredClone(before),metered:[row],attempts:[{request_id:'r',attempt_index:0,deployment_id:deployment,provider:'groq',model_reference:model,served:true,facts_digest:'digest',cost_amount:null}]},canary:{ok:true,firstHttpStatus:200,retryHttpStatus:409,clientRequestId:'fixture',requestId:'r',authority:{credentialId:'wl'},usage:[{unit:'output_tokens',quantity:2}],provider:'groq'}};
}
const run=f=>requireSettledOperation(f.before,f.after,f.canary);
test('explicit canonical direct admission uses the complete admitted tuple when final tuple is all NULL',()=>{const f=fixture();assert.equal(run(f).request_id,'r');assert.equal(f.after.metered[0].final_authorized_provider,null);});
test('complete approved final authorization remains accepted',()=>{const f=fixture(),r=f.after.metered[0];for(const field of ['model_reference','provider','deployment_id'])r[`final_authorized_${field}`]=r[`admitted_${field}`];assert.equal(run(f).request_id,'r');});
test('partial NULL or omitted final authorization is refused',()=>{for(const field of ['model_reference','provider','deployment_id']){for(const value of [undefined,fixture().after.metered[0][`admitted_${field}`]]){const f=fixture();f.after.metered[0][`final_authorized_${field}`]=value;assert.throws(()=>run(f),/final_route_differs/);}}});
test('foreign requested/admitted/resolved routes are refused even with complete valid final tuple',()=>{for(const field of ['requested_model_reference','admitted_model_reference','admitted_provider','admitted_deployment_id','resolved_model_reference']){const f=fixture(),r=f.after.metered[0];for(const k of ['model_reference','provider','deployment_id'])r[`final_authorized_${k}`]=r[`admitted_${k}`];r[field]='foreign';assert.throws(()=>run(f),/final_route_differs/);}});
test('serving provider must match the effective authorization and the caller',()=>{for(const target of ['row','caller']){const f=fixture();if(target==='row')f.after.metered[0].serving_provider='cerebras';else f.canary.provider='cerebras';assert.throws(()=>run(f),/final_route_differs/);}});
test('exact authorized served attempt is required, unknown cost stays NULL',()=>{for(const mutate of [f=>f.after.attempts[0].served=false,f=>{const d=Object.keys(DEPLOYMENTS)[0];f.after.attempts[0].deployment_id=d;f.after.attempts[0].provider=DEPLOYMENTS[d];}]){const f=fixture();mutate(f);assert.throws(()=>run(f),/exact_attempts_missing_or_foreign/);}const f=fixture();run(f);assert.equal(f.after.attempts[0].cost_amount,null);});
